name: EZEN mini Frontend Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.12.0
          cache: 'npm'

      - name: Check Node.js version
        run: node -v

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.AWS_EZEN_SSH_PRIVATE_KEY }}

      - name: Add GitHub to known_hosts
        run: |
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Update Git Remote URL
        run: |
          git remote set-url origin git@github.com:joshbae119/ezen-mini-frontend.git

      - name: Debug SSH Connection
        run: |
          ssh -o "StrictHostKeyChecking=no" -o "BatchMode=yes" ubuntu@3.37.2.236 'echo "SSH connection successful"'

      - name: Deploy to AWS EC2
        run: |
          ssh -o StrictHostKeyChecking=no -o "BatchMode=yes" ubuntu@3.37.2.236 << 'EOF'
            set -e  # 에러 발생 시 즉시 스크립트 중단

            echo "Navigating to project directory..."
            cd /home/bitnami/hira2 || { echo "Failed to change directory"; exit 1; }

            echo "Current directory contents:"
            ls -al

            echo "Updating git remote and pulling latest changes..."
            git remote set-url origin git@github.com:joshbae119/ezen-mini-frontend.git
            git fetch origin main || { echo "Git fetch failed"; exit 1; }
            git reset --hard origin/main || { echo "Git reset failed"; exit 1; }

            echo "Installing dependencies..."
            npm install || { echo "npm install failed"; exit 1; }

            echo "Building the project..."
            npm run build || { echo "Build failed"; exit 1; }

            echo "Restarting PM2 processes..."
            pm2 restart all || { echo "PM2 restart failed"; exit 1; }
            pm2 save || { echo "PM2 save failed"; exit 1; }

            echo "Deployment completed successfully"
          EOF
