export const questions = [
  { id: 1, dimension:'TF', text:'1', options:['A. 손부터 냅다 잡고 납치해서 떡집부터 가고 얘기한다.','B. 떡집은 후순위! 친구랑 먼저 얘기한다.'] },
  { id: 2, dimension:'TF', text:'2', options:['A. 떡집/간헐천 등을 이용하여 단시간에 효율 양작을 한다.','B. 느긋하게 즐기면서 하는게 중요하다.'] },
  { id: 3, dimension:'EI', text:'3', options:['A. 많은 친구가 항상 접속 중이다.','B. 항상 여유가 있다.'] },
  { id: 4, dimension:'JP', text:'4', options:['A. 매일 빛반사까지 해야 일과가 끝난 기분이다.','B. 서로 며칠씩 여유롭게 주고 받아도 상관없다.'] },
  { id: 5, dimension:'TF', text:'5', options:['A. 스카이는 각자도생. 강하게 키워야 한다.','B. 새우 어그로는 내가 다 가져간다.'] },
  { id: 6, dimension:'EI', text:'6', options:['A. 친구들과 다함께 노는 것이 좋다.','B. 솔로 플레이를 선호한다.'] },
  { id: 7, dimension:'JP', text:'7', options:['A. 항상 재화에 여유가 있도록 관리한다.','B. 위시도 없는데 굳이 관리할 필요가 없다.'] },
  { id: 8, dimension:'TF', text:'8', options:['A. 언제 돌아올지 모르니 일단 두고 간다.','B. 친구가 돌아올 때까지 최대한 옆을 지킨다.'] },
  { id: 9, dimension:'EI', text:'9', options:['A. 쉽게 친구가 될 수 있다.','B. 신중하게 친구를 맺는다.'] },
  { id:10, dimension:'JP', text:'10', options:['A. 매일 정해진 양만큼의 일퀘/양작을 해야 한다.','B. 일퀘만 하고 다른 컨텐츠를 즐긴다.'] },
  { id:11, dimension:'EI', text:'11', options:['A. 내가 합류하는 편이다.','B. 상대가 합류해주길 기다린다.'] },
  { id:12, dimension:'TF', text:'12', options:['A. 빛만 주고 받는 빛지니스','B. 간간히 대화도 하는 교류가 있는 스친.'] },
  { id:13, dimension:'JP', text:'13', options:['A. 꼭 수집하는 편이다.','B. 아이템 몇 개 정도는 놓쳐도 괜찮다.'] },
  { id:14, dimension:'EI', text:'14', options:['A. 살갑게 인사하는 편이다.','B. 말걸기 전에는 가만히 있거나 제스처로만 간단하게 인사한다.'] },
  { id:15, dimension:'JP', text:'15', options:['A. 물약이 충분할 때만 키도박을 시도한다.','B. 물약이 세개만 있어도 시도해본다.'] },
]
