name: Ezen-NextJS CICD V1

on:
  push:
    branches: ['main'] # main 브랜치에 코드가 푸시될 때 트리거
  pull_request:
    branches: ['main'] # main 브랜치에 대한 PR 생성/업데이트 시 트리거

jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04

    environment: EZEN # GitHub 환경 설정 (Environments에서 'EZEN' 사용)

    env: # 공통 환경 변수 설정
      HOST: ${{ secrets.EC2_EZEN_NEXTJS_HOST }}
      USER: ${{ secrets.EC2_EZEN_NEXTJS_USER }}

    steps:
      # 1. 리포지토리 체크아웃 (GitHub Actions용)
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. SSH 키 설정
      - name: Configure SSH Key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_EZEN_NEXTJS_KEY }}
        run: |
          set -e  # 에러 발생 시 즉시 중단
          mkdir -p ~/.ssh  # ~/.ssh 디렉토리 생성 (이미 존재해도 안전)
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts

      # 3. EC2에서 Git Pull 실행
      - name: Update Source Code on EC2
        run: |
          set -e  # 에러 발생 시 즉시 중단
          ssh $USER@$HOST << 'EOF'
            if [ ! -d /home/ubuntu/ezen-nextjs ]; then
              echo "Directory not found. Cloning repository..."
              git clone https://github.com/<username>/<repository>.git /home/ubuntu/ezen-nextjs
            else
              echo "Directory exists. Resetting and pulling latest changes..."
              cd /home/ubuntu/ezen-nextjs
              git reset --hard HEAD  # 로컬 변경 사항 삭제
              git pull
            fi
          EOF

      # 4. EC2에서 의존성 설치 및 Next.js 빌드
      - name: Install Dependencies and Build on EC2
        run: |
          set -e  # 에러 발생 시 즉시 중단
          ssh $USER@$HOST << 'EOF'
            cd /home/ubuntu/ezen-nextjs
            npm install  # 의존성 설치
            npm run build  # Next.js 빌드 실행
          EOF

      # 5. EC2에서 애플리케이션 실행
      - name: Deploy Application on EC2
        run: |
          set -e  # 에러 발생 시 즉시 중단
          ssh $USER@$HOST << 'EOF'
            cd /home/ubuntu/ezen-nextjs
            pm2 stop ezen-nextjs || true  # 기존 애플리케이션 중지 (없어도 무시)
            pm2 start npm --name "ezen-nextjs" -- run start  # 애플리케이션 시작
            pm2 save  # PM2 프로세스 저장
          EOF
