name: EZEN mini Frontend Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    # 기존 ubuntu-latest 대신 self-hosted runner(aws-ec2)를 사용
    runs-on: [self-hosted, aws-ec2]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.12.0
          cache: 'npm'

      - name: Check Node.js version
        run: node -v

      - name: Debug Secrets Length
        run: |
          if [ -z "${{ secrets.AWS_EZEN_SSH_PRIVATE_KEY }}" ]; then
            echo "ERROR: Secret AWS_EZEN_SSH_PRIVATE_KEY is empty or not set."
            exit 1
          else
            echo "Secret AWS_EZEN_SSH_PRIVATE_KEY is set and has a non-zero length."
          fi

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.AWS_EZEN_SSH_PRIVATE_KEY }}

      - name: Debug SSH Key Loading
        run: |
          ssh-add -L || { echo "No SSH keys added to the agent."; exit 1; }

      - name: Add GitHub to known_hosts
        run: |
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Update Git Remote URL
        run: |
          git remote set-url origin git@github.com:joshbae119/ezen-mini-frontend.git

      - name: Debug SSH Connection
        run: |
          ssh -o "StrictHostKeyChecking=no" -o "BatchMode=yes" ubuntu@3.37.2.236 'echo "SSH connection successful"'

      - name: Deploy to AWS EC2
        run: |
          ssh -o StrictHostKeyChecking=no -o "BatchMode=yes" ubuntu@3.37.2.236 << 'EOF'
            set -e  # 에러 발생 시 즉시 스크립트 중단

            echo "Navigating to project directory..."
            cd /home/ubuntu/ezen-mini-frontend || { echo "Failed to change directory"; exit 1; }

            echo "Current directory contents:"
            ls -al

            echo "Updating git remote and pulling latest changes..."
            git remote set-url origin git@github.com:joshbae119/ezen-mini-frontend.git
            git fetch origin main || { echo "Git fetch failed"; exit 1; }
            git reset --hard origin/main || { echo "Git reset failed"; exit 1; }

            echo "Installing dependencies..."
            npm install || { echo "npm install failed"; exit 1; }

            echo "Building the project..."
            npm run build || { echo "Build failed"; exit 1; }

            echo "Restarting PM2 processes gracefully..."
            if pm2 list | grep -q "ezen-mini-frontend"; then
              pm2 reload ezen-mini-frontend || { echo "PM2 reload failed"; exit 1; }
            else
              pm2 start npm --name "ezen-mini-frontend" -- start || { echo "PM2 start failed"; exit 1; }
            fi
            pm2 save || { echo "PM2 save failed"; exit 1; }

            echo "Deployment completed successfully"
          EOF
